MOTECH-1636 Upgrade to HttpClient v4.4.1
Upgrading HttpClient v4.4.1 resolves a known issue in
v4.4 that results in NoClassDefFoundError:
org/apache/http/ssl/SSLContexts when using the library
in an OSGi environment.

Change-Id: I74092a2ab93abeb4c52b4631cfee417c0be87585